<form id='account' class='LabUserForm' action='./' method='post'>
  <div class='row'>
    <div class='four columns'>
      <label for='old_pass'>Current Password</label>
      <input class='u-full-width' type='password' id='old_pass' name='old_pass' required='1' placeholder='' value=''></input>
    </div>
    <div class='four columns'>
      <label for='new_pass'>New Password</label>
      <input class='u-full-width' type='password' id='new_pass' name='new_pass' required='1' placeholder='' value=''></input>
    </div>
    <div class='four columns'>
      <label for='confirm_new_pass'>Confirm New Password</label>
      <input class='u-full-width' type='password' id='confirm_new_pass' name='confirm_new_pass' required='1' placeholder='' value=''></input>
    </div>
  </div>
  <div class='row'>
    <div class='twelve columns'>
      <input class='' type='submit' id='change_pass' name='change_pass' required='0' placeholder='' value='Change Password'></input>
    </div>
  </div>
</form>
