<form id='login' class='LabUserForm' action='./' method='post'>
  <div class='row'>
    <div class='six columns'>
      <label for='user'>Username</label>
      <input class='u-full-width' type='text' id='user' name='user' required='1' placeholder='' value=''></input>
    </div>
    <div class='six columns'><label for='pass'>Password</label>
      <input class='u-full-width' type='password' id='pass' name='pass' required='1' placeholder='' value=''></input>
    </div>
  </div>
  <div class='row'>
    <div class='twelve columns'>
      <input class='' type='submit' id='login' name='login' required='0' placeholder='' value='Login'></input>
    </div>
  </div>
</form>
