<?php
/**
 * A²Fab Lab items Manager Module
 *
 * Developed for the A² Fab Lab at the University of Florida.
 * Lists all item files in an admin tab page.
 * Item pages are listing for different items for which students can
 * be charged in the charge system. Holds information relevant to the
 * Peoplesoft Student Financials format.
 *
 * Thomas R Storey, 2015
 * Licensed under MIT License, see LICENSE.TXT
 *
 * http://fablab.arts.ufl.edu
 * https://github.com/UF-Asq-Fab-Lab
 *
 */

class ProcessItem extends ProcessPageType {
  static public function getModuleInfo(){
    return array(
      'title' => 'ProcessItem',
      'version' => 100,
      'summary' => 'Lists all item files in an admin tab page.',
      'permanent' => false,
      'permission' => 'item-admin',
      'requires' => array('LabUser>=1.0.0'),
      'icon' => 'dollar',
      'useNavJSON' => true
      );
  }

  protected $lister = null;

  public function __construct() {
    $this->set('showFields', array('name'));
    if(wire('modules')->isInstalled("LabUser")){
      $this->set('showFields', array('title', 'type_code', 'description'));
    }
    $this->set('addLabel', $this->_('Add New'));
    $this->set('jsonListLabel', 'title'); // what to use for 'label' property in JSON nav data
  }

  public function init() {
    parent::init();
    $this->template = $this->wire('templates')->get("name=item");
    $this->lister = $this->wire('modules')->get("ProcessPageLister");
  }

  protected function getLister($selector = '') {
    $selector = "template=item, include=all, check_access=0, $selector";
    $lister = $this->lister;
    if(!$lister)return null;
    $lister->editMode = ProcessPageLister::windowModeDirect;
    $properties = array(
      'initSelector' => $selector,
      'columns' => $this->showFields,
      'defaultSelector' => "type_code%=",
      'defaultSort' => 'title',
      'parent' => $this->page,
      'template' => $this->template,
      'editURL' => './edit',
      'addURL' => './add/',
      'allowSystem' => false,
      'allowIncludeAll' => true
      );
    foreach($properties as $name => $val) {
      $lister->$name = $val;
    }
    return $lister;
  }

  protected function renderList($selector = '', $pageOptions = array()) {
    $lister = $this->getLister($selector);
    if(!$lister) return parent::renderList($selector, $pageOptions);
    return $lister->execute();
  }

  public function executeConfig() {
    return $this->getLister()->executeConfig();
  }

  public function executeViewport() {
    return $this->getLister()->executeViewport();
  }

  public function executeReset() {
    return $this->getLister()->executeReset();
  }

  public function executeActions() {
    return $this->getLister()->executeActions();
  }

  public function ___executeEdit() {
    $this->addHookAfter('ProcessPageEdit::buildForm', $this, 'hookBuildForm');
    return parent::___executeEdit();
  }

  public function hookBuildForm(HookEvent $event) {
    $form = $event->return;
    // Is this how you make forms look nice in the admin?
    $theme = $form->getChildByName('admin_theme');
    if(!$theme) return;
    if(!$theme->attr('value')) {
      $theme->attr('value', $this->wire('config')->defaultAdminTheme);
    }
  }

  public function ___install(){
    $parent = $this->wire('pages')->get("name=charge");
    $p = new Page();
    $p->template = "admin";
    $p->name = "itmes";
    $p->title = "Items";
    $p->process = $this;
    $p->parent = $parent;
    $p->save();
    parent::___install();
  }

  public function ___executeNavJSON(array $options = array()) {
    $itemPages = $this->wire('pages')->find("template=item");
    $parentID = $this->page->id;
    $itemArray = array();
    foreach($itemPages as $up) {
      $itemArray[] = $up;
    }
    $options['items'] = $itemArray;
    $options['itemLabel'] = 'title';
    $options['add'] = "add/?parent_id=".$parentID;
    return parent::___executeNavJSON($options);
  }

}

?>
