<form id='reset_request' class='LabUserForm' action='./' method='post'>
  <div class='row'>
    <div class='six columns'>
      <label for='email'>Email Address Associated with your Account</label>
      <input class='u-full-width' type='email' id='email' name='email' required='1' placeholder='' value=''></input>
    </div>
    <div class='six columns'>
      <label for='ufid'>Your UFID</label>
      <input class='u-full-width' type='text' id='ufid' name='ufid' required='1' placeholder='########' value=''></input>
    </div>
  </div>
  <div class='row'>
    <div class='twelve columns'>
      <input class='' type='submit' id='reset' name='reset' required='0' placeholder='' value='Send New Password'></input>
    </div>
  </div>
</form>
